remove shopt&alias to make it work on powershell
geopython/geopython-workshop pull request #131
Opened 2023-06-21 09:58 UTC by pvgenuchten

PR to facilitate discussion on this topic

docker-compose was removed >1 year ago, i think we can assume all are migrated by now?

removing shopt and alias because it is not supported on powershell/windows

todo: update docs for windows:
syntax:  bash geopython-workshop-ctl.sh start|stop|url|update

2023-06-21 11:29 UTC, pvgenuchten commented
@tomkralidis, updated docs for powershell

2023-06-21 12:05 UTC, justb4 requested changes
Hm, looks like these changes remove the alias and assume the command is `docker compose`. This will break for students having `docker-compose` installed (like me).

Best option is to make the script cross-platform. The `$IsWindows` var e.g.
and https://redmondmag.com/articles/2020/08/18/cross-platform-powershell-scripts.aspx

2023-06-21 14:09 UTC, pvgenuchten commented
ah, good to know people are still using docker-compose

alternative would be to duplicate the script and rename the powershell variant to .ps1

2023-06-21 14:55 UTC, justb4 requested changes

2023-06-21 14:55 UTC, justb4 commented on workshop/geopython-workshop-ctl.ps.sh
> +    platform="$(uname | tr '[:upper:]' '[:lower:]')"
is this still required? I guess the `openapp="cmd /c start"` is the command in PS here.

2023-06-22 09:11 UTC, justb4 commented
I cannot test this, but seems useful. I wonder if the `uname` stuff even works. I have no idea how Powershell relates to WSL and Docker install. I have the feeling we would not need a separate Bash script with some smart 'sniffing' line the `$Windows` var and `uname` command, branching in the original script. It may be confusing even, two scripts with almost identical names.

2025-07-03 12:54 UTC, tomkralidis commented
Bumping @pvgenuchten in case we want to add this for FOSS4 EU 2025.

2025-07-04 11:21 UTC, pvgenuchten commented
superseded by #203

2025-07-04 11:21 UTC, closed without merging