Converted docs to using material theme
geopython/geopython-workshop pull request #132
Opened 2023-06-21 12:09 UTC by krishnaglodha

Converted docs to using mkdocs with material theme. 

I have added new `mkdocs.yml` file . I have also added custom js and css code for `termy`

2023-06-21 16:12 UTC, tomkralidis requested changes

2023-06-21 16:12 UTC, tomkralidis commented on web/docs/assets/javascripts/old_custom.js
Remove this file.

2023-06-21 16:12 UTC, tomkralidis commented on web/docs/assets/stylesheets/old_custom.css
Remove this file.

2023-06-22 03:37 UTC, krishnaglodha commented on web/docs/index.md
> -# start the workshop
If I add `#` 
```
<div class="termy">

```console
curl -O https://codeload.github.com/geopython/geopython-workshop/zip/master
unzip master
cd geopython-workshop-master/workshop

# start the workshop
./geopython-workshop-ctl.sh start
# display URL and open in default web browser
./geopython-workshop-ctl.sh url
# stop workshop
./geopython-workshop-ctl.sh stop
```

</div>
```
<img width="718" alt="Screenshot 2023-06-22 at 9 06 34 AM" src="https://github.com/geopython/geopython-workshop/assets/47075664/a6d14774-5d78-4c4c-99fb-a6fc65a576b1">

2023-06-23 00:10 UTC, merged