added code to load vector data on raster
geopython/geopython-workshop pull request #137
Opened 2023-06-22 03:54 UTC by krishnaglodha

PR for issue #111

added code block of overlay raster on vector

2023-06-22 09:03 UTC, justb4 commented
Think this is up to @ldesousa . also given timing, or make OPTIONAL.

2023-06-22 14:49 UTC, ldesousa commented
Will have a look, but might be better to also leave this for afterwards.

2023-06-23 07:39 UTC, ldesousa requested changes

2023-06-23 07:39 UTC, ldesousa commented on workshop/jupyter/content/notebooks/05-raster-data.ipynb
> +    "import geopandas as gpd\n",
Missing pyplot import at least.

2023-06-23 07:39 UTC, ldesousa commented on workshop/jupyter/content/notebooks/05-raster-data.ipynb
> +  {
Please place this cell after the contour lines example (currently cell 19).

2025-07-11 12:15 UTC, tomkralidis commented
Closing PR, keeping issue open for future implementation.

2025-07-11 12:15 UTC, closed without merging